name: Deploy to Hetzner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            cd ~/server-infrastructure/portfolio-backend/auth-currency-data-hub
            git pull
            cd ..
            docker-compose stop auth-service
            docker-compose rm -f auth-service
            docker-compose up --build -d auth-service




